### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jenniferxuu** [dsuess/mediapipe-addons#2]
Hello @dsuess ! I cloned your repo within a mediapipe repo (so it could have access to all the mediapipe utils and calculators) - however, when I run the build command, I run into these error which I'm not sure how to resolve:
<img width="772" alt="image" src="https://github.com/dsuess/mediapipe-pytorch/assets/93094899/d1f5c8c1-96bc-45f3-945a-d77530760e9a">
Thanks!

**Comment by dsuess** [comment]
This has likely to do with WORKSPACE referencing the `master` branch of `rules_foreign_cc`: https://github.com/dsuess/mediapipe-pytorch/blob/master/WORKSPACE#L51C10-L51C57. However, that repo has renamed the branch to `main`. 

Note that most of that WORKSPACE file was copy-pasted from the same file in the media pipe repo, so just check out their rule for `rules_foreign_cc`: https://github.com/google/mediapipe/blob/master/WORKSPACE#L47

However, note that this repo is relatively outdated, so you probably want to update to a more recent version of media pipe anyway.

**Comment by jenniferxuu** [comment]
I see! To make sure I'm understanding correctly, I should use the mediapipe repo's rules for `rules_foreign.cc` instead of the one currently in your repo?

**Comment by dsuess** [comment]
That would be my first guess. There's a chance that the version specified there is too new, then you either need to update other packages in WORKSPACE or try to figure out which version of `rules_foreign` works with the current setup through trial-and-error

**Comment by jenniferxuu** [comment]
Gotcha, thank you so much!
